//
//  BSSASearchContactsInteractor.swift
//  BSSASearchContacts
//
//  Created Branchbit on 12/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BASASearchContactsInteractor: BASASearchContactsInteractorProtocol {

    weak var presenter: BASASearchContactsPresenterProtocol?
}
