//
//  BSSASearchContactsPresenter.swift
//  BSSASearchContacts
//
//  Created Branchbit on 12/05/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BASASearchContactsPresenter: BASASearchContactsPresenterProtocol {

    weak private var view: BASASearchContactsViewProtocol?
    var interactor: BASASearchContactsInteractorProtocol?
    private let router: BASASearchContactsWireframeProtocol

    init(interface: BASASearchContactsViewProtocol, interactor: BASASearchContactsInteractorProtocol?, router: BASASearchContactsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
